### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by quozl** [sugarlabs/mancala-activity#7]
- [ ] update NEWS (if present), update version, tag the release, for reference see [Fructose base activity module release process](https://wiki.sugarlabs.org/go/Development_Team/Release#Fructose_.28base_activity.29_modules), though Mancala isn't in Fructose,
- [x] make bundle, using the `dist_xo` target of `setup.py`,
- [ ] test bundle on an instance of Sugar by installing using Browse; by downloading the bundle from within Browse, then starting the activity,
- [x] upload bundle to activities.sugarlabs.org, writing release notes for teachers and learners.

**Comment by yell0wfl4sh** [comment]
@quozl can you please explain me how to do 2nd and 3rd task here!

**Comment by quozl** [comment]
@yashagrawal3, issue text updated, but please be more specific about what you don't know how to do.  You might also search the wiki for dist_xo.

**Comment by yell0wfl4sh** [comment]
All four tasks completed and released the new version( i.e. 23) on 
http://activities.sugarlabs.org/en-US/sugar/addon/4420

**Comment by quozl** [comment]
- [x] please tag the released commit `v23` and push that tag to this repository.

Once you've done that, GitHub will show a Release in the repository view.

**Comment by yell0wfl4sh** [comment]
Done! Also tested the activity after downloading it from the browser.

**Comment by quozl** [comment]
Actually, you've tagged a commit 6ac4b959bb79aa6c13316dadc61a88dcaaf9f2fd in your repository, not in this repository.  Here is how I fixed it;
* checked out the master branch of this repository,
* move the tag `git tag --force v23`,
* push the tag `git push --force --tags`.

**Comment by yell0wfl4sh** [comment]
Thanks! updated my repository.
