### ISSUE TITLE
Upgrade sugargame

### ISSUE THREAD

**Issue by quozl** [sugarlabs/mancala-activity#8]
A new version of [sugargame](https://github.com/sugarlabs/sugargame) is available which fixes startup delay.

**Comment by rhl-bthr** [comment]
@quozl I would like to work on this

**Comment by quozl** [comment]
If you like.  Let me know how you go.  I've tried, and am having trouble.  I'm worried that it might be a fault in sugargame that I've only just introduced, so I'm holding off on releasing v1.2 of sugargame until this activity works with it.

**Comment by rhl-bthr** [comment]
@quozl Thanks, Sure. I will let you know of the problems I face

**Comment by quozl** [comment]
@Pro-Panda, testing on Ubuntu 18.04 the Pygame window did not render, and I found that sugargame realize callback was triggered before run_pygame, so I changed that in the local version to accept modules and main in the constructor.  Now I'm trying to figure out why the game does not begin.

See https://github.com/sugarlabs/mancala-activity/tree/sugargame-v1.2 for my work in progress.

**Comment by rhl-bthr** [comment]
@quozl Thanks for the update :)

**Comment by quozl** [comment]
Cause of not rendering was `g.init()` setting `g.w` and `g.h` to 1 at a time the surface had not negotiated up to the correct size.

**Comment by quozl** [comment]
So I did try rewriting `g.init()` but it became impractical and then `self.manc` needed work done to accept a changed size, so I decided to delay calling `g.init` until the display size was known.

Please test https://github.com/sugarlabs/mancala-activity/commit/b0eb77a5c95f21bd4ac58ad4200b006ac4b329fe ... the game does start properly again.

Once you've tested, I'll refine the patch and prepare a sugargame release.

**Comment by rhl-bthr** [comment]
**Tested:** b0eb77a

**Output:** Game starts as expected, no issues observed

**Tested on:** 
 - Ubuntu 16.04
 - Sugar 0.112
 - rdesktop

**Comment by quozl** [comment]
https://github.com/sugarlabs/mancala-activity/commit/1c77266a736de531c284c0f7b69e89162f0a82e4
